[project]
name = "bitcoin-energy-assets"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/stx-cross-chain-oraclee/bitcoin-energy-assets/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.bitcoin-energy-assets]
path = "contracts/bitcoin-energy-assets.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
